### ISSUE TITLE
Removed from google playstore

### ISSUE THREAD

**Issue by boredness** [Rouji/Hupl#15]
So it looks like the app was removed from the playstore?

**Comment by Rouji** [comment]
Yeah, they changed some requirements for apps and want me to put in some details about Hupl (age appropriateness and things like that) in the play store developer console thing. I didn't get around to it in time, so the app went off the store for a bit.
The problem is if I now go and try to put that in, it just throws exceptions at me whenever I submit pretty much *any* form.

![gg](https://user-images.githubusercontent.com/17692001/80649609-ac4f3b80-8a72-11ea-8d67-1650dc54e9a6.png)

Well done, Google. 💯

**Comment by boredness** [comment]
Have you checked into that email they sent you? maybe some further information in there.

**Comment by Rouji** [comment]
@boredness I know perfectly well what they want, it's just the website that's kind of borked.

**Comment by Rouji** [comment]
https://play.google.com/store/apps/details?id=eu.imouto.hupl
I've managed to save the stuff at some point and it's back now.
